Test: support multiple assignments for `@testset let` (JuliaLang/julia#50151)
Nested `ContextTestset` is  supported, so we can stack it when there are
multiple assignments in a given `let` block.

```julia
julia> @testset let logi = log(im), op = !iszero
           @test imag(logi) == π/2
           @test op(real(logi))
       end
Test Failed at none:3
  Expression: !(iszero(real(logi)))
     Context: logi = 0.0 + 1.5707963267948966im
              op = !iszero

ERROR: There was an error during testing
```